from coordenacao.serializers.alunoSerializer import AlunoSerializer
from coordenacao.serializers.disciplinaSerializer import DisciplinaSerializer
from coordenacao.serializers.tarefaSerializer import TarefaSerializer